# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currentStatus.ui'
#
# Created: Wed Apr  9 15:58:50 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import conf.language.lang as langmodule

class Ui_statusDialog(object):
    def setupUi(self, statusDialog):
        statusDialog.setObjectName("statusDialog")
        statusDialog.resize(837, 538)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        statusDialog.setFont(font)
        statusDialog.setAutoFillBackground(False)
        self.gridLayoutWidget = QtGui.QWidget(statusDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 60, 801, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblLastUpdateTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblLastUpdateTitle.setObjectName("lblLastUpdateTitle")
        self.gridLayout_2.addWidget(self.lblLastUpdateTitle, 2, 0, 1, 1)
        self.lblNextPUpdateTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblNextPUpdateTitle.setObjectName("lblNextPUpdateTitle")
        self.gridLayout_2.addWidget(self.lblNextPUpdateTitle, 11, 0, 1, 1)
        self.lblSchedTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblSchedTitle.setObjectName("lblSchedTitle")
        self.gridLayout_2.addWidget(self.lblSchedTitle, 8, 0, 1, 1)
        self.lblAVGvalue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblAVGvalue.setFont(font)
        self.lblAVGvalue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAVGvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAVGvalue.setObjectName("lblAVGvalue")
        self.gridLayout_2.addWidget(self.lblAVGvalue, 1, 2, 1, 2)
        self.lblDatabaseValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblDatabaseValue.setFont(font)
        self.lblDatabaseValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblDatabaseValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDatabaseValue.setObjectName("lblDatabaseValue")
        self.gridLayout_2.addWidget(self.lblDatabaseValue, 4, 2, 1, 2)
        self.lblLicenceValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblLicenceValue.setFont(font)
        self.lblLicenceValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblLicenceValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLicenceValue.setObjectName("lblLicenceValue")
        self.gridLayout_2.addWidget(self.lblLicenceValue, 3, 2, 1, 2)
        self.lblOADTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblOADTitle.setObjectName("lblOADTitle")
        self.gridLayout_2.addWidget(self.lblOADTitle, 7, 0, 1, 1)
        self.lblNextVUpdateTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblNextVUpdateTitle.setObjectName("lblNextVUpdateTitle")
        self.gridLayout_2.addWidget(self.lblNextVUpdateTitle, 9, 0, 1, 1)
        self.lblLastUpdateValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblLastUpdateValue.setFont(font)
        self.lblLastUpdateValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblLastUpdateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLastUpdateValue.setObjectName("lblLastUpdateValue")
        self.gridLayout_2.addWidget(self.lblLastUpdateValue, 2, 2, 1, 2)
        self.lblDatabaseTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblDatabaseTitle.setObjectName("lblDatabaseTitle")
        self.gridLayout_2.addWidget(self.lblDatabaseTitle, 4, 0, 1, 1)
        self.lblNextVUpdateValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblNextVUpdateValue.setFont(font)
        self.lblNextVUpdateValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblNextVUpdateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNextVUpdateValue.setObjectName("lblNextVUpdateValue")
        self.gridLayout_2.addWidget(self.lblNextVUpdateValue, 9, 2, 1, 2)
        self.lblLicenceTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblLicenceTitle.setObjectName("lblLicenceTitle")
        self.gridLayout_2.addWidget(self.lblLicenceTitle, 3, 0, 1, 1)
        self.lblDBDateTitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblDBDateTitle.setObjectName("lblDBDateTitle")
        self.gridLayout_2.addWidget(self.lblDBDateTitle, 5, 0, 1, 1)
        self.lblSchedValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblSchedValue.setFont(font)
        self.lblSchedValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblSchedValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSchedValue.setObjectName("lblSchedValue")
        self.gridLayout_2.addWidget(self.lblSchedValue, 8, 2, 1, 2)
        self.lblOADValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblOADValue.setFont(font)
        self.lblOADValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblOADValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOADValue.setObjectName("lblOADValue")
        self.gridLayout_2.addWidget(self.lblOADValue, 7, 2, 1, 2)
        self.lblAVGtitle = QtGui.QLabel(self.gridLayoutWidget)
        self.lblAVGtitle.setObjectName("lblAVGtitle")
        self.gridLayout_2.addWidget(self.lblAVGtitle, 1, 0, 1, 1)
        self.lblDBDateValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblDBDateValue.setFont(font)
        self.lblDBDateValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblDBDateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDBDateValue.setObjectName("lblDBDateValue")
        self.gridLayout_2.addWidget(self.lblDBDateValue, 5, 2, 1, 2)
        self.lblNextPUpdateValue = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lblNextPUpdateValue.setFont(font)
        self.lblNextPUpdateValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblNextPUpdateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNextPUpdateValue.setObjectName("lblNextPUpdateValue")
        self.gridLayout_2.addWidget(self.lblNextPUpdateValue, 11, 2, 1, 2)
        self.lblAVGtitle_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.lblAVGtitle_3.setFont(font)
        self.lblAVGtitle_3.setObjectName("lblAVGtitle_3")
        self.gridLayout_2.addWidget(self.lblAVGtitle_3, 0, 1, 1, 2)
        self.lblAVGtitle_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.lblAVGtitle_2.setFont(font)
        self.lblAVGtitle_2.setObjectName("lblAVGtitle_2")
        self.gridLayout_2.addWidget(self.lblAVGtitle_2, 6, 1, 1, 2)
        self.btnExit = QtGui.QPushButton(statusDialog)
        self.btnExit.setGeometry(QtCore.QRect(330, 480, 150, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMinimumSize(QtCore.QSize(150, 50))
        self.btnExit.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnExit.setFont(font)
        self.btnExit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnExit.setObjectName("btnExit")
        self.label_12 = QtGui.QLabel(statusDialog)
        self.label_12.setGeometry(QtCore.QRect(340, 0, 141, 61))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/avg_logo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(statusDialog)
        QtCore.QMetaObject.connectSlotsByName(statusDialog)

    def retranslateUi(self, statusDialog):
        statusDialog.setWindowTitle(QtGui.QApplication.translate("statusDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLastUpdateTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.lastUpdateTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblNextPUpdateTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.nextProgramUpdate, None, QtGui.QApplication.UnicodeUTF8))
        self.lblSchedTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.schedStatusTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblAVGvalue.setText(QtGui.QApplication.translate("statusDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDatabaseValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLicenceValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOADTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.oadStatusTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblNextVUpdateTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.nextiAVIupdate, None, QtGui.QApplication.UnicodeUTF8))
        self.lblLastUpdateValue.setText(QtGui.QApplication.translate("statusDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDatabaseTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.aviUsedTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblNextVUpdateValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLicenceTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.licenceTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblDBDateTitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.aviDateTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblSchedValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOADValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAVGtitle.setText(QtGui.QApplication.translate("statusDialog", langmodule.avgTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.lblDBDateValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNextPUpdateValue.setText(QtGui.QApplication.translate("statusDialog", "Αριθμός Άδειας / Έκδοση Άδειας", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAVGtitle_3.setText(QtGui.QApplication.translate("statusDialog", langmodule.programInfo, None, QtGui.QApplication.UnicodeUTF8))
        self.lblAVGtitle_2.setText(QtGui.QApplication.translate("statusDialog", langmodule.serviceStatusTitle, None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("statusDialog", langmodule.btnExitTitle, None, QtGui.QApplication.UnicodeUTF8))

import avg_rc
