# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanSettings.ui'
#
# Created: Fri Nov 15 18:55:37 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_scanSettingsDialog(object):
    def setupUi(self, scanSettingsDialog):
        scanSettingsDialog.setObjectName("scanSettingsDialog")
        scanSettingsDialog.setWindowModality(QtCore.Qt.WindowModal)
        scanSettingsDialog.resize(540, 500)
        scanSettingsDialog.setMinimumSize(QtCore.QSize(540, 500))
        scanSettingsDialog.setMaximumSize(QtCore.QSize(540, 500))
        self.verticalLayoutWidget = QtGui.QWidget(scanSettingsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 501, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkbIfType = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbIfType.setObjectName("chkbIfType")
        self.verticalLayout.addWidget(self.chkbIfType)
        self.textIfType = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.textIfType.setMinimumSize(QtCore.QSize(0, 40))
        self.textIfType.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textIfType.setObjectName("textIfType")
        self.verticalLayout.addWidget(self.textIfType)
        self.chkbFileStore = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbFileStore.setObjectName("chkbFileStore")
        self.verticalLayout.addWidget(self.chkbFileStore)
        self.btnSelectFolder = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnSelectFolder.setEnabled(False)
        self.btnSelectFolder.setAutoDefault(False)
        self.btnSelectFolder.setObjectName("btnSelectFolder")
        self.verticalLayout.addWidget(self.btnSelectFolder)
        self.textStoreFile = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.textStoreFile.setEnabled(False)
        self.textStoreFile.setMinimumSize(QtCore.QSize(0, 40))
        self.textStoreFile.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textStoreFile.setObjectName("textStoreFile")
        self.verticalLayout.addWidget(self.textStoreFile)
        self.chkbBackUpFiles = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbBackUpFiles.setObjectName("chkbBackUpFiles")
        self.verticalLayout.addWidget(self.chkbBackUpFiles)
        self.chkbArchive = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbArchive.setObjectName("chkbArchive")
        self.verticalLayout.addWidget(self.chkbArchive)
        self.chkbBootSec = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbBootSec.setObjectName("chkbBootSec")
        self.verticalLayout.addWidget(self.chkbBootSec)
        self.chkbCookies = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbCookies.setObjectName("chkbCookies")
        self.verticalLayout.addWidget(self.chkbCookies)
        self.chkbMultimedia = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkbMultimedia.setObjectName("chkbMultimedia")
        self.verticalLayout.addWidget(self.chkbMultimedia)
        self.labelHandle = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHandle.sizePolicy().hasHeightForWidth())
        self.labelHandle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.labelHandle.setFont(font)
        self.labelHandle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelHandle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHandle.setObjectName("labelHandle")
        self.verticalLayout.addWidget(self.labelHandle)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioDelete = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioDelete.setObjectName("radioDelete")
        self.horizontalLayout.addWidget(self.radioDelete)
        self.radioHeal = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioHeal.setObjectName("radioHeal")
        self.horizontalLayout.addWidget(self.radioHeal)
        self.radioVault = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioVault.setObjectName("radioVault")
        self.horizontalLayout.addWidget(self.radioVault)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(scanSettingsDialog)
        self.frame.setGeometry(QtCore.QRect(200, 570, 120, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelLogo = QtGui.QLabel(scanSettingsDialog)
        self.labelLogo.setGeometry(QtCore.QRect(230, 0, 71, 31))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(":/avg_logo.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.btnOK = QtGui.QPushButton(scanSettingsDialog)
        self.btnOK.setGeometry(QtCore.QRect(150, 450, 101, 31))
        self.btnOK.setObjectName("btnOK")
        self.btnExit = QtGui.QPushButton(scanSettingsDialog)
        self.btnExit.setGeometry(QtCore.QRect(280, 450, 101, 31))
        self.btnExit.setObjectName("btnExit")

        self.retranslateUi(scanSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(scanSettingsDialog)

    def retranslateUi(self, scanSettingsDialog):
        scanSettingsDialog.setWindowTitle(QtGui.QApplication.translate("scanSettingsDialog", "Ρυθμίσεις Αναζήτησης", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbIfType.setText(QtGui.QApplication.translate("scanSettingsDialog", "Σάρωση συγκεκριμένων τύπων αρχείων", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbFileStore.setText(QtGui.QApplication.translate("scanSettingsDialog", "Αποθήκευση αποτελεσμάτων σε αρχείο", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFolder.setText(QtGui.QApplication.translate("scanSettingsDialog", "Επιλογή Φακέλου Αποθήκευσης", None, QtGui.QApplication.UnicodeUTF8))
        self.textStoreFile.setToolTip(QtGui.QApplication.translate("scanSettingsDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Εισάγετε εδώ το όνομα του αρχείου στο οποίο θα αποθηκευτεί το αποτέλεσμα αναζήτησης...</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbBackUpFiles.setText(QtGui.QApplication.translate("scanSettingsDialog", "Διατήρηση αντιγράφων αρχείων που πρόκειται να διαγραφούν ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbArchive.setText(QtGui.QApplication.translate("scanSettingsDialog", "Σάρωση archive files (.zip, .rar κ.λ.π.)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbBootSec.setText(QtGui.QApplication.translate("scanSettingsDialog", "Αναζήτηση στον τομέα εκκίνησης (boot sector)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbCookies.setText(QtGui.QApplication.translate("scanSettingsDialog", "Αναζήτηση στα cookies", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbMultimedia.setText(QtGui.QApplication.translate("scanSettingsDialog", "Να μη γίνει αναζήτηση σε πολυμεσικά αρχεία", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHandle.setText(QtGui.QApplication.translate("scanSettingsDialog", "Χειρισμός Μολυσμένων Αρχείων", None, QtGui.QApplication.UnicodeUTF8))
        self.radioDelete.setText(QtGui.QApplication.translate("scanSettingsDialog", "Διαγραφή", None, QtGui.QApplication.UnicodeUTF8))
        self.radioHeal.setText(QtGui.QApplication.translate("scanSettingsDialog", "Αποκατάσταση", None, QtGui.QApplication.UnicodeUTF8))
        self.radioVault.setText(QtGui.QApplication.translate("scanSettingsDialog", "Αποκλεισμός", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("scanSettingsDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("scanSettingsDialog", "Άκυρο", None, QtGui.QApplication.UnicodeUTF8))

import avg_rc
