# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateSettings.ui'
#
# Created: Fri Nov 15 18:55:38 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dialogUpdateSettings(object):
    def setupUi(self, dialogUpdateSettings):
        dialogUpdateSettings.setObjectName("dialogUpdateSettings")
        dialogUpdateSettings.setWindowModality(QtCore.Qt.WindowModal)
        dialogUpdateSettings.resize(623, 660)
        dialogUpdateSettings.setMinimumSize(QtCore.QSize(623, 660))
        dialogUpdateSettings.setMaximumSize(QtCore.QSize(623, 660))
        self.layoutWidget = QtGui.QWidget(dialogUpdateSettings)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 40, 491, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblInterrupt = QtGui.QLabel(self.layoutWidget)
        self.lblInterrupt.setMinimumSize(QtCore.QSize(0, 30))
        self.lblInterrupt.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblInterrupt.setFont(font)
        self.lblInterrupt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInterrupt.setObjectName("lblInterrupt")
        self.gridLayout_2.addWidget(self.lblInterrupt, 0, 0, 1, 2)
        self.lblMinSpeed = QtGui.QLabel(self.layoutWidget)
        self.lblMinSpeed.setMinimumSize(QtCore.QSize(350, 0))
        self.lblMinSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMinSpeed.setObjectName("lblMinSpeed")
        self.gridLayout_2.addWidget(self.lblMinSpeed, 1, 0, 1, 1)
        self.lblMaxTime = QtGui.QLabel(self.layoutWidget)
        self.lblMaxTime.setObjectName("lblMaxTime")
        self.gridLayout_2.addWidget(self.lblMaxTime, 2, 0, 1, 1)
        self.leditMinSpeed = QtGui.QLineEdit(self.layoutWidget)
        self.leditMinSpeed.setObjectName("leditMinSpeed")
        self.gridLayout_2.addWidget(self.leditMinSpeed, 1, 1, 1, 1)
        self.leditMaxTime = QtGui.QLineEdit(self.layoutWidget)
        self.leditMaxTime.setObjectName("leditMaxTime")
        self.gridLayout_2.addWidget(self.leditMaxTime, 2, 1, 1, 1)
        self.label = QtGui.QLabel(dialogUpdateSettings)
        self.label.setGeometry(QtCore.QRect(250, 10, 91, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/avg_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget1 = QtGui.QWidget(dialogUpdateSettings)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 205, 551, 361))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.lblProxy = QtGui.QLabel(self.layoutWidget1)
        self.lblProxy.setMinimumSize(QtCore.QSize(0, 30))
        self.lblProxy.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblProxy.setFont(font)
        self.lblProxy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblProxy.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProxy.setObjectName("lblProxy")
        self.gridLayout.addWidget(self.lblProxy, 0, 0, 1, 3)
        self.lblProxyPass = QtGui.QLabel(self.layoutWidget1)
        self.lblProxyPass.setObjectName("lblProxyPass")
        self.gridLayout.addWidget(self.lblProxyPass, 7, 0, 1, 1)
        self.lblProxyMode = QtGui.QLabel(self.layoutWidget1)
        self.lblProxyMode.setObjectName("lblProxyMode")
        self.gridLayout.addWidget(self.lblProxyMode, 1, 0, 1, 1)
        self.lblProxyName = QtGui.QLabel(self.layoutWidget1)
        self.lblProxyName.setObjectName("lblProxyName")
        self.gridLayout.addWidget(self.lblProxyName, 2, 0, 1, 1)
        self.lblProxyUsername = QtGui.QLabel(self.layoutWidget1)
        self.lblProxyUsername.setObjectName("lblProxyUsername")
        self.gridLayout.addWidget(self.lblProxyUsername, 6, 0, 1, 1)
        self.lblUseLogIn = QtGui.QLabel(self.layoutWidget1)
        self.lblUseLogIn.setObjectName("lblUseLogIn")
        self.gridLayout.addWidget(self.lblUseLogIn, 4, 0, 1, 1)
        self.lblProxyAuthType = QtGui.QLabel(self.layoutWidget1)
        self.lblProxyAuthType.setObjectName("lblProxyAuthType")
        self.gridLayout.addWidget(self.lblProxyAuthType, 5, 0, 1, 1)
        self.leditProxyPass = QtGui.QLineEdit(self.layoutWidget1)
        self.leditProxyPass.setObjectName("leditProxyPass")
        self.gridLayout.addWidget(self.leditProxyPass, 7, 1, 1, 2)
        self.chkUseLogin = QtGui.QCheckBox(self.layoutWidget1)
        self.chkUseLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkUseLogin.setText("")
        self.chkUseLogin.setObjectName("chkUseLogin")
        self.gridLayout.addWidget(self.chkUseLogin, 4, 1, 1, 2)
        self.cmbBoxProxyAuthType = QtGui.QComboBox(self.layoutWidget1)
        self.cmbBoxProxyAuthType.setObjectName("cmbBoxProxyAuthType")
        self.gridLayout.addWidget(self.cmbBoxProxyAuthType, 5, 1, 1, 2)
        self.leditProxyName = QtGui.QLineEdit(self.layoutWidget1)
        self.leditProxyName.setObjectName("leditProxyName")
        self.gridLayout.addWidget(self.leditProxyName, 2, 1, 1, 2)
        self.cmbBoxProxyMode = QtGui.QComboBox(self.layoutWidget1)
        self.cmbBoxProxyMode.setObjectName("cmbBoxProxyMode")
        self.gridLayout.addWidget(self.cmbBoxProxyMode, 1, 1, 1, 2)
        self.leditProxyUsername = QtGui.QLineEdit(self.layoutWidget1)
        self.leditProxyUsername.setObjectName("leditProxyUsername")
        self.gridLayout.addWidget(self.leditProxyUsername, 6, 1, 1, 2)
        self.leditProxyPort = QtGui.QLineEdit(self.layoutWidget1)
        self.leditProxyPort.setObjectName("leditProxyPort")
        self.gridLayout.addWidget(self.leditProxyPort, 3, 1, 1, 1)
        self.lblProxyPort = QtGui.QLabel(self.layoutWidget1)
        self.lblProxyPort.setObjectName("lblProxyPort")
        self.gridLayout.addWidget(self.lblProxyPort, 3, 0, 1, 1)
        self.btnOK = QtGui.QPushButton(dialogUpdateSettings)
        self.btnOK.setGeometry(QtCore.QRect(320, 580, 141, 51))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnOK.setFont(font)
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtGui.QPushButton(dialogUpdateSettings)
        self.btnCancel.setGeometry(QtCore.QRect(170, 580, 141, 51))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(dialogUpdateSettings)
        QtCore.QMetaObject.connectSlotsByName(dialogUpdateSettings)

    def retranslateUi(self, dialogUpdateSettings):
        dialogUpdateSettings.setWindowTitle(QtGui.QApplication.translate("dialogUpdateSettings", "Ρυθμίσεις Ενημέρωσης Λογισμικού και Βάσης Ιών", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInterrupt.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Συνθήκες διακοπής διαδικασίας ενημέρωσης λογισμικού", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinSpeed.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Ελάχιστη Ταχύτητα (bytes / sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaxTime.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Χρονικό Διάστημα (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxy.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Ρυθμίσεις σχετικά με χρήση διακομιστή Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyPass.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Κωδικός Χρήστη (password)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyMode.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Χρήση Διακομιστή Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyName.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Όνομα Διακομιστή Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyUsername.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Όνομα Χρήστη (username)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUseLogIn.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Απαιτείται Log In στον Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyAuthType.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Τύπος Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProxyPort.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Θύρα Διακομιστή Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("dialogUpdateSettings", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("dialogUpdateSettings", "Ακύρωση", None, QtGui.QApplication.UnicodeUTF8))

import avg_rc
